chore: embed-services package
looker-open-source/sdk-codegen pull request #1254
Opened 2023-02-27 22:54 UTC by josephaxisa

This is just a skeleton of the package that will contain the service layer for looker embed components.

2023-02-27 23:00 UTC, jkaster requested changes
You should update the main repo LICENSE file for the current copyright year

2023-02-27 23:00 UTC, jkaster commented on packages/embed-services/package.json
> +    "access": "public"
I think you want this private for now

2023-02-27 23:00 UTC, jkaster commented on packages/embed-services/src/index.ts
> + Copyright (c) 2022 Looker Data Sciences, Inc.
Yes, just let the linter do its thing. It's based on the `LICENSE` from the main folder, which should be updated to 2023, then your local `LICENSE` file matches.

2023-02-28 00:34 UTC, jkaster reviewed
got a question before approval

2023-02-28 00:34 UTC, jkaster commented on packages/embed-services/package.json
> +  "private": false,
should this be `true` or `false`?

2023-02-28 02:10 UTC, josephaxisa commented on packages/embed-services/package.json
> +  "private": false,
good catch, thanks.

2023-02-28 02:36 UTC, jkaster approved these changes

2023-02-28 03:14 UTC, merged