[Python] Bump attrs version
looker-open-source/sdk-codegen pull request #374
Opened 2020-11-05 08:37 UTC by setu4993

Ran into a weird edge case today where import for `looker_sdk` failed because of a version issue with `attrs`, which was on `19.3.0` but `cattrs` required `20.1.0`+. Tracelog below, but running a `pip install -U attrs` fixed the issue. Bumping it up in here, along with the version (feel free to update the version appropriately if that's an error on my end).

Tracelog:
```sh
...
/opt/conda/lib/python3.7/site-packages/looker_sdk/__init__.py in <module>
     25 from looker_sdk.rtl import api_settings
     26 from looker_sdk.rtl import requests_transport
---> 27 from looker_sdk.rtl import serialize
     28 from looker_sdk.rtl import auth_session
     29 

/opt/conda/lib/python3.7/site-packages/looker_sdk/rtl/serialize.py in <module>
     37 )
     38 
---> 39 import cattr
     40 
     41 from looker_sdk.rtl import model

/opt/conda/lib/python3.7/site-packages/cattr/__init__.py in <module>
----> 1 from .converters import Converter, GenConverter, UnstructureStrategy
      2 from .gen import override
      3 
      4 __all__ = (
      5     "global_converter",

/opt/conda/lib/python3.7/site-packages/cattr/converters.py in <module>
     14 )
     15 
---> 16 from attr import fields, resolve_types
     17 
     18 from ._compat import (

ImportError: cannot import name 'resolve_types' from 'attr' (/opt/conda/lib/python3.7/site-packages/attr/__init__.py)
```

2020-11-05 18:08 UTC, joeldodge79 commented
thanks for finding this. We need to maintain support for python 3.6 and it looks like that was dropped in [`cattrs 1.1.0`](https://github.com/Tinche/cattrs/blob/master/HISTORY.rst#110-2020-10-29) so we'll need to either pin `cattrs == 1.0.0` or find a fancy way of switching based on python version (similar to how `python-dateutil` and `typing-extensions` are added)

2020-11-05 18:11 UTC, joeldodge79 requested changes
If you have cycles to figure out allowing higher `cattrs` versions conditional on python version that would be much appreciated! Otherwise for now let's just pin it to `1.0.0` so new installations aren't broken

2020-11-05 18:34 UTC, setu4993 commented
Thanks Joel! I can get this in place later today.

2020-11-06 06:34 UTC, setu4993 commented
@joeldodge79 : Done. Tested installing on my brand new venvs on 36 and 37, and the right versions get installed on both.

2020-11-06 17:18 UTC, joeldodge79 approved these changes
Awesome, thank you! I'll get this published shortly

2020-11-06 17:18 UTC, merged

2020-11-06 18:19 UTC, setu4993 commented
Thanks Joel!

2020-11-06 19:19 UTC, joeldodge79 commented
https://pypi.org/project/looker-sdk/0.1.3b20/ is up