feat(python): Add Flask app example
looker-open-source/sdk-codegen pull request #519
Opened 2021-03-23 05:01 UTC by izzymiller

I find that despite being questionable for production, Flask is hands down the easiest way to stand up a complete Python application. I figured we ought to have an easy to dissect example of Flask and Looker working in concert.

This PR effectively clones the canonical [Flask tutorial](https://flask.palletsprojects.com/en/1.1.x/tutorial/) and adds some very lightweight Looker functionality that's easy to understand and extend.

It's pretty lightweight and self explanatory but let me know if you think I should better document the code, or change anything structurally.

## Developer Checklist [ℹ️](https://github.com/looker-open-source/sdk-codegen/blob/main/CONTRIBUTING.md#developer-checklist)

**most do not apply as this is just an example**
- [ ] ♿️ Accessibility addressed
- [ ] 🌏 Localization & Internationalization addressed
- [ ] 🖼 Image Snapshot coverage
- [ ] 📚 Documentation updated
- [ ] 🧳 Bundle size impact addressed
- [ ] 🏁 Performance impacts addressed
- [X] 👾 Browsers tested
    - [X] Chrome
    - [X] Firefox
    - [X] Safari
    - [X] IE11

2021-03-23 14:47 UTC, joeldodge79 requested changes
nice work @izzymiller - just a couple style nits but otherwise LGTM

2021-03-23 14:47 UTC, joeldodge79 commented on examples/python/lookersdk-flask/app/__init__.py
> +from . import looker
unused?

2021-03-23 14:47 UTC, joeldodge79 commented on examples/python/lookersdk-flask/app/__init__.py
> +from flask import Flask
[the goog](https://g3doc.corp.google.com/eng/doc/devguide/py/style/index.md?cl=head#s2.2-imports) wants it like this: `import flask` (see suggested change below)

2021-03-23 14:47 UTC, joeldodge79 commented on examples/python/lookersdk-flask/app/__init__.py
> +    app = Flask(__name__, instance_relative_config=True)
```suggestion
    app = flask.Flask(__name__, instance_relative_config=True)
```

2021-03-23 14:47 UTC, joeldodge79 commented on examples/python/lookersdk-flask/app/auth.py
> +from .looker import get_my_user
ditto on import style here and etc

2021-03-23 23:47 UTC, izzymiller commented on examples/python/lookersdk-flask/app/__init__.py
> +from . import looker
Need em all except looker, but good callout.

2021-03-24 00:00 UTC, joeldodge79 approved these changes

2021-03-24 00:01 UTC, merged

2021-03-25 12:26 UTC, josephaxisa commented
I am late to the party but wanted to say thanks for putting this together, looks great!