feat: lots of RunIt form cleanup
looker-open-source/sdk-codegen pull request #814
Opened 2021-09-09 18:29 UTC by jkaster

Made some changes to the **RunIt** form, both for layout and editing various values
 
## Bug fixes

- enum values are now a string input instead of `{}`. There is an outstanding task to support a dropdown picker for enums that will come with the next significant change for the form editor
- DelimArray values are now a string input instead of `{}`

## Design improvements

- all inputs are on a single line now, saving form space. This is particularly useful for endpoints with many input values
- date time picker is now a pop over with a button to choose the date
- the default action for the form is now the first button, making it more convenient for tabbing through

2021-09-10 11:00 UTC, josephaxisa requested changes
Looking great, liking these changes! While you're at it, could you please add unit tests to:
1) ensure that when a date is picked, the corresponding state param value is what you'd expect it to be 
2) enum values are string inputs and the state is updated with what we expect to be sent over the wire 
3) ditto for DelimArray values

2021-09-14 00:25 UTC, jkaster commented on packages/run-it/src/components/LoginForm/LoginForm.tsx
> +      <Button key="loginButton" onClick={handleLogin}>
Removed key again

2021-09-14 00:25 UTC, jkaster commented on packages/run-it/src/components/RequestForm/formUtils.tsx
> +      key={`${name}_pop`}
Added myself. Didn't want to risk the Google cla bot issue

2021-09-14 00:26 UTC, jkaster commented on packages/api-explorer/src/scenes/MethodScene/utils.ts
> +const editType = (spec: IApiModel, type: IType) => {
I've added the comment but GithHub is currently refusing to display the update.

2021-09-14 08:37 UTC, josephaxisa commented on packages/run-it/src/components/RequestForm/formUtils.tsx
> +      key={`${name}_pop`}
Fair. It's definitely fixed now though, at least it had no complaints on my last PR

2021-09-14 09:09 UTC, josephaxisa reviewed
Looks good to me! Some design-related feedback that may be worth discussing is 
- the whitespace between form inputs and their labels and how it affects the form presentation when there are no inputs:
![image](https://user-images.githubusercontent.com/19397662/133228199-b9971e41-bf38-44d8-971d-bcbc42a8a1aa.png)
![image](https://user-images.githubusercontent.com/19397662/133228530-17f4d03d-59d7-4b5c-8c0c-7589fac25497.png)
- toggle switches get "squashed" if there's a lengthy description:
![toggle switches](https://user-images.githubusercontent.com/19397662/133229527-35406db0-559a-4e8b-ba27-d2bf53453a12.gif)

2021-09-14 16:55 UTC, jkaster commented on packages/run-it/src/components/ShowResponse/responseUtils.tsx
> +
We could. I'd like to see how the transpiled code is different, if at all

2021-09-14 17:08 UTC, josephaxisa commented
@jhardy do you have any thoughts about the above two points by any chance?

2021-09-14 17:13 UTC, josephaxisa approved these changes
caught up with John and we agreed to address any design feedback in a separate PR. This is ready to merge as is.

2021-09-14 17:14 UTC, jkaster commented on packages/run-it/src/components/ShowResponse/responseUtils.tsx
> +
Looks like it's just stylistic so no reason to enforce a different syntax

2021-09-14 17:15 UTC, merged