feat: makeTheCall for Kotlin and type tagging
looker-open-source/sdk-codegen pull request #833
Opened 2021-09-22 02:30 UTC by jkaster

Draft PR for hack week
- prettifies TypeScript `makeTheCall()` with evidently no node infection
- passes all unit tests for Kotlin `makeTheCall()`
- when #827 is merged into this branch, it will also include type tagging for better type scrolling.

2021-10-01 16:01 UTC, josephaxisa requested changes

2021-10-01 16:25 UTC, jkaster commented on packages/api-explorer/src/components/DocMethodSummary/utils.tsx
> +  switch (status.toLowerCase()) {
yes. internally I don't think we'll be translating status. If it's not the case when we localize, we'l have to change this logic anyway.

2021-10-01 16:25 UTC, jkaster commented on packages/api-explorer/src/components/DocResponses/DocResponseTypes.tsx
> +  }, [responses, mediaTypes])
lint complaint

2021-10-01 16:26 UTC, jkaster commented on kotlin/src/test/TestSmoke.kt
> +        val ids = DelimArray<Long>(userIds)
Yeah, understanding Kotlin slightly better since I wrote that

2021-10-01 16:29 UTC, jkaster commented on packages/run-it/src/components/RequestForm/RequestForm.spec.tsx
> +    test.todo('clicking run with an invalid body shows a messagebar')
There is now

2021-10-01 18:56 UTC, jkaster commented on packages/api-explorer/src/components/ExploreType/ExploreType.tsx
> +import { buildPath } from '../DocReferences/utils'
moved

2021-10-05 14:38 UTC, josephaxisa approved these changes
LGTM. Very useful changes.

2021-10-05 14:42 UTC, merged