feat: Update Kotlin SDK to use Gson instead of Jackson
looker-open-source/sdk-codegen pull request #836
Opened 2021-09-24 09:53 UTC by mistryrakesh

This PR updates the kotlin SDK to use Gson instead of Jackson for serialization (We were already using gson to deserialize).

This fixes:
- Jackson serialization bug [Jackson renames primitive boolean field by removing 'is'](https://stackoverflow.com/questions/32270422/jackson-renames-primitive-boolean-field-by-removing-is) resulting in much clean and concise code.
- In some cases prevents breaking of the SDK due to API changes by ignoring unknown fields ([How to decode JSON with unknown field using Gson?](https://stackoverflow.com/a/20442943)). e.g. When SDK is generated from an older instance but has to access a newer instance.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/looker-open-source/sdk-codegen/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [x] Appropriate docs were updated (if necessary)

Fixes #825 🦕

2021-09-24 15:30 UTC, jkaster requested changes
Great update. Nice to have cleaner and more flexible code.

```sh
bin/smoke kotlin
```
passes.

Can you add a test that verifies the graceful handling of unknown fields?

2021-09-25 17:19 UTC, mistryrakesh commented
Hey @jkaster thanks for reviewing!

I have added a smoke test (`SmokeTest.testIgnoreUnknownFields()`) which basically fetches all users and deserializes it into `DummyUser` object. The `DummyUser` class is a subset of the `User` class. When the server sends a response `User` object the Gson deserializer ignores extra properties and creates the `DummyUser` object.

Using the Jackson deserializer the test fails with error:
```
java.lang.Error: GET /users com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "avatar_url" (class DummyUser), not marked as ignorable (4 known properties: "display_name", "id", "credentials_api3", "email"])
 at [Source: (StringReader); line: 1, column: 1260] (through reference chain: java.lang.Object[][0]->DummyUser["avatar_url"]).message
java.lang.AssertionError: java.lang.Error: GET /users com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "avatar_url" (class DummyUser), not marked as ignorable (4 known properties: "display_name", "id", "credentials_api3", "email"])
 at [Source: (StringReader); line: 1, column: 1260] (through reference chain: java.lang.Object[][0]->DummyUser["avatar_url"]).message
	at org.junit.Assert.fail(Assert.java:88)
	at kotlin.test.junit.JUnitAsserter.fail(JUnitSupport.kt:56)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:226)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:236)
	at kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.AssertionsKt__AssertionsKt.assertTrue(Assertions.kt:40)
	at kotlin.test.AssertionsKt.assertTrue(Unknown Source)
	at TestSmoke.testIgnoreUnknownFields(TestSmoke.kt:212)
```

2021-09-25 21:32 UTC, jkaster commented
@mistryrakesh This is great stuff! I really appreciate you contributions here.

2021-09-25 21:34 UTC, jkaster approved these changes
Nicely done! It's great to have better resilience for the Kotlin SDK.

2021-09-25 21:34 UTC, jkaster commented on kotlin/src/test/TestSmoke.kt
> + * Dummy user data class based on [User] but with a subset of its properties.
Perfect

2021-09-26 02:10 UTC, mistryrakesh commented on kotlin/src/test/TestSmoke.kt
> + * Dummy user data class based on [User] but with a subset of its properties.
Thanks!

2021-09-26 02:11 UTC, merged